In [1]:
# word embedding in python

In [2]:
import tensorflow as tf

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
from tensorflow.keras.models import Sequential

In [10]:
from tensorflow.keras.layers import Flatten

In [11]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

In [12]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [14]:
import numpy as np
import pandas as pd

In [15]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [17]:
# vocab_size demonstrate
one_hot('amazing restaurant',30)

[14, 29]

In [19]:
vocab_size = 50
encoded_reviews = [one_hot(r,vocab_size) for r in reviews]
encoded_reviews

[[20, 47],
 [41, 11],
 [11, 43],
 [18, 47, 40],
 [24, 32, 22],
 [2, 47],
 [5, 32, 32],
 [15, 4],
 [15, 49],
 [11, 44]]

In [20]:
# padding the encoded values
max_length = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen = max_length,padding="post")

In [21]:
padded_reviews

array([[20, 47,  0],
       [41, 11,  0],
       [11, 43,  0],
       [18, 47, 40],
       [24, 32, 22],
       [ 2, 47,  0],
       [ 5, 32, 32],
       [15,  4,  0],
       [15, 49,  0],
       [11, 44,  0]])

In [23]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))


In [24]:
x =padded_reviews
y=sentiment

In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [27]:
model.fit(x, y, epochs=50, verbose=0)

In [29]:
loss, accuracy = model.evaluate(x, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step - accuracy: 1.0000 - loss: 0.6068


1.0

In [30]:
loss

0.6067813634872437

In [31]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [32]:
weights[13]

array([ 0.01797444, -0.03491493, -0.0479493 , -0.03774613, -0.03610315],
      dtype=float32)

In [33]:
weights[4]

array([-0.08729015, -0.02828007,  0.09148672,  0.08147226,  0.08632858],
      dtype=float32)

In [35]:
weights[16]

array([-0.00803806,  0.00662496,  0.03745848, -0.02253547, -0.01016055],
      dtype=float32)